/*DECLARACAO DE VARIAVEIS*/

DECLARE @DATAATUAL DATETIME
DECLARE @MES_ATUAL INT
DECLARE @ANO_ATUAL INT
DECLARE @COD_IND INT
DECLARE @HONORARIOS_CONSULTAS DECIMAL(12,2)
DECLARE @HONORARIOS_CONSULTAS_MEDINTERNO_CONVENIO DECIMAL(12,2)
DECLARE @HONORARIOS_CONSULTAS_MEDEXTERNO_CONVENIO DECIMAL(12,2)
DECLARE @HONORARIOS_CONSULTAS_MEDINTERNO_PARTICULAR DECIMAL(12,2)
DECLARE @HONORARIOS_CONSULTAS_MEDEXTERNO_PARTICULAR DECIMAL(12,2)
DECLARE @HONORARIOS_CONSULTAS_NC_PARTICULAR DECIMAL(12,2)

/*PEGA O ANO E MES ATUAL*/
SET @MES_ATUAL = 2
SET @ANO_ATUAL = 2015
SET @DATAATUAL = GETDATE()

/*DECLARA O CODIGO DO INDICADOR A SER ALIMENTADO*/
SET @COD_IND = 678


/*HONORÁRIOS CONSULTAS CONVÊNIO MÉDICO INTERNO*/
SELECT O.OSM_SERIE AS "SÉRIE", O.OSM_NUM AS "NÚMERO", convert(varchar(2),month(O.OSM_DTHR))+'/'+convert(varchar(4),year(O.OSM_DTHR)) as "MÊS/ANO", I.SMM_NUM AS "ITEM", I.SMM_COD AS "CÓDIGO", P.SMK_NOME AS "DESCRIÇÃO", I.SMM_MED AS "MÉDICO", C.CNV_NOME AS "CONVÊNIO", I.SMM_STR AS "SETOR", I.SMM_QT AS "QUANTIDADE", ISNULL(I.SMM_VLR,0) AS "VALOR", ((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL1,0))
		+(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL2,0))
		+(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL6,0)))*0.88
		FROM HOSSRVSMART.SMART.DBO.SMM I, 			
		HOSSRVSMART.SMART.DBO.SMK P,
		HOSSRVSMART.SMART.DBO.CNV C, 						
		HOSSRVSMART.SMART.DBO.OSM O,
		HOSSRVSMART.SMART.DBO.HON H
		WHERE I.SMM_OSM = O.OSM_NUM
			AND I.SMM_OSM_SERIE = O.OSM_SERIE
			AND I.SMM_HON_SEQ = H.HON_SEQ
			AND MONTH(O.OSM_DTHR) = @MES_ATUAL
			AND YEAR(O.OSM_DTHR) = @ANO_ATUAL
			AND I.SMM_SFAT <> 'C'
			AND I.SMM_TIPO_FATURA = 'E'
			AND I.SMM_COD = P.SMK_COD 
			AND I.SMM_TPCOD  = P.SMK_TIPO
			AND (I.SMM_STR = 'JCO' OR I.SMM_STR = 'JCH' OR I.SMM_STR = 'JCM')
			AND I.SMM_COD <> 'CONSUCOH' 
			AND (I.SMM_MED = '2845'/*ALLAN LUZ*/
				OR I.SMM_MED = '3429'/*Ana Candida*/
				OR I.SMM_MED = '2081'/*CLÉCIA VILANOVA*/
				OR I.SMM_MED = '2044'/*DANILO AMARAL*/
				OR I.SMM_MED = '19150'/*EUDO MENDONÇA*/
				OR I.SMM_MED = '2518'/*FÁBIO MORAIS*/
				OR I.SMM_MED = '1707'/*FÁBIO RIBAS*/
				OR I.SMM_MED = '3519'/*GUSTAVO MELO*/
				OR I.SMM_MED = '2036'/*JOAQUIM FONTES*/

				OR I.SMM_MED = '4366'/*Lydianne Lumack do Monte Agra*/
				OR I.SMM_MED = '1885'/*MÁRCIO PIMENTA*/
				OR I.SMM_MED = '935'/*MÁRIO URSULINO*/
				OR I.SMM_MED = '2245'/*MÕNICA ANDRADE*/
				OR I.SMM_MED = '3579'/*NAYANA MAYNART*/
				OR I.SMM_MED = '3616'/*TANIA NUNES*/
				OR I.SMM_MED = '903'/*JOSÉ FERREIRA*/)
			AND O.OSM_CNV = C.CNV_COD
			AND C.CNV_CAIXA_FATURA = 'F' 
			AND SMM_PAC_REG NOT IN (SELECT PAC_REG 
						FROM PAC 
						WHERE PAC_NOME LIKE '%TESTE %')

/*HONORÁRIOS CONSULTAS CONVÊNIO MÉDICO EXTERNO*/
SELECT O.OSM_SERIE AS "SÉRIE", O.OSM_NUM AS "NÚMERO", convert(varchar(2),month(O.OSM_DTHR))+'/'+convert(varchar(4),year(O.OSM_DTHR)) as "MÊS/ANO", I.SMM_NUM AS "ITEM", I.SMM_COD AS "CÓDIGO", P.SMK_NOME AS "DESCRIÇÃO", I.SMM_MED AS "MÉDICO", C.CNV_NOME AS "CONVÊNIO", I.SMM_STR AS "SETOR", I.SMM_QT AS "QUANTIDADE", ISNULL(I.SMM_VLR,0) AS "VALOR", ((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL1,0))
		+(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL2,0))
		+(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL6,0)))*0.83
		FROM HOSSRVSMART.SMART.DBO.SMM I, 			
		HOSSRVSMART.SMART.DBO.SMK P, 
		HOSSRVSMART.SMART.DBO.CNV C, 						
		HOSSRVSMART.SMART.DBO.OSM O,
		HOSSRVSMART.SMART.DBO.HON H
		WHERE I.SMM_OSM = O.OSM_NUM
			AND I.SMM_OSM_SERIE = O.OSM_SERIE
			AND I.SMM_HON_SEQ = H.HON_SEQ
			AND MONTH(O.OSM_DTHR) = @MES_ATUAL
			AND YEAR(O.OSM_DTHR) = @ANO_ATUAL
			AND I.SMM_SFAT <> 'C'
			AND I.SMM_TIPO_FATURA = 'E'
			AND I.SMM_COD = P.SMK_COD 
			AND I.SMM_TPCOD  = P.SMK_TIPO
			AND (I.SMM_STR = 'JCO' OR I.SMM_STR = 'JCH' OR I.SMM_STR = 'JCM')
			AND I.SMM_COD <> 'CONSUCOH' 
			AND I.SMM_MED <> '2845'/*ALLAN LUZ*/
			and I.SMM_MED <> '3429'/*Ana Candida*/
			and I.SMM_MED <> '2081'/*CLÉCIA VILANOVA*/
			and I.SMM_MED <> '2044'/*DANILO AMARAL*/
			and I.SMM_MED <> '19150'/*EUDO MENDONÇA*/
			and I.SMM_MED <> '2518'/*FÁBIO MORAIS*/
			and I.SMM_MED <> '1707'/*FÁBIO RIBAS*/
			and I.SMM_MED <> '3519'/*GUSTAVO MELO*/
			and I.SMM_MED <> '2036'/*JOAQUIM FONTES*/

			and I.SMM_MED <> '4366'/*Lydianne Lumack do Monte Agra*/
			and I.SMM_MED <> '1885'/*MÁRCIO PIMENTA*/
			and I.SMM_MED <> '935'/*MÁRIO URSULINO*/
			and I.SMM_MED <> '2245'/*MÕNICA ANDRADE*/
			and I.SMM_MED <> '3579'/*NAYANA MAYNART*/
			and I.SMM_MED <> '3616'/*TANIA NUNES*/
			and I.SMM_MED <> '903'/*JOSÉ FERREIRA*/
			AND O.OSM_CNV = C.CNV_COD 
			AND  O.OSM_CNV <> 'PFE' 
			AND  O.OSM_CNV <> 'PCN' 
			AND  O.OSM_CNV <> 'PTL'
			AND C.CNV_CAIXA_FATURA = 'F' 
			AND SMM_PAC_REG NOT IN (SELECT PAC_REG 
						FROM PAC 
						WHERE PAC_NOME LIKE '%TESTE %')


/*HONORÁRIOS CONSULTAS PARTICULAR MÉDICO INTERNO*/
SELECT O.OSM_SERIE AS "SÉRIE", O.OSM_NUM AS "NÚMERO", convert(varchar(2),month(O.OSM_DTHR))+'/'+convert(varchar(4),year(O.OSM_DTHR)) as "MÊS/ANO", I.SMM_NUM AS "ITEM", I.SMM_COD AS "CÓDIGO", P.SMK_NOME AS "DESCRIÇÃO", I.SMM_MED AS "MÉDICO", C.CNV_NOME AS "CONVÊNIO", I.SMM_STR AS "SETOR", I.SMM_QT AS "QUANTIDADE", ISNULL(I.SMM_VLR,0) AS "VALOR", ((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL1,0))
		+(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL2,0))
		+(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL6,0)))*0.88
		FROM HOSSRVSMART.SMART.DBO.SMM I, 			
		HOSSRVSMART.SMART.DBO.SMK P,
		HOSSRVSMART.SMART.DBO.MTE M, 
		HOSSRVSMART.SMART.DBO.CNV C,  						
		HOSSRVSMART.SMART.DBO.OSM O,
		HOSSRVSMART.SMART.DBO.HON H
		WHERE I.SMM_OSM = O.OSM_NUM
			AND I.SMM_OSM_SERIE = O.OSM_SERIE
			AND I.SMM_HON_SEQ = H.HON_SEQ
			AND MONTH(O.OSM_DTHR) = @MES_ATUAL
			AND YEAR(O.OSM_DTHR) = @ANO_ATUAL
			AND M.MTE_OSM_SERIE = O.OSM_SERIE
			AND M.MTE_OSM = O.OSM_NUM
			AND M.MTE_STATUS = 'D'
			AND M.MTE_IND_REC_NF = 'F'
			AND I.SMM_COD = P.SMK_COD 
			AND I.SMM_TPCOD  = P.SMK_TIPO
			AND (I.SMM_STR = 'JCO' OR I.SMM_STR = 'JCH' OR I.SMM_STR = 'JCM')
			AND I.SMM_COD <> 'CONSUCOH' 
			AND (I.SMM_MED = '2845'/*ALLAN LUZ*/
				OR I.SMM_MED = '3429'/*Ana Candida*/
				OR I.SMM_MED = '2081'/*CLÉCIA VILANOVA*/
				OR I.SMM_MED = '2044'/*DANILO AMARAL*/
				OR I.SMM_MED = '19150'/*EUDO MENDONÇA*/
				OR I.SMM_MED = '2518'/*FÁBIO MORAIS*/
				OR I.SMM_MED = '1707'/*FÁBIO RIBAS*/
				OR I.SMM_MED = '3519'/*GUSTAVO MELO*/
				OR I.SMM_MED = '2036'/*JOAQUIM FONTES*/

				OR I.SMM_MED = '4366'/*Lydianne Lumack do Monte Agra*/
				OR I.SMM_MED = '1885'/*MÁRCIO PIMENTA*/
				OR I.SMM_MED = '935'/*MÁRIO URSULINO*/
				OR I.SMM_MED = '2245'/*MÕNICA ANDRADE*/
				OR I.SMM_MED = '3579'/*NAYANA MAYNART*/
				OR I.SMM_MED = '3616'/*TANIA NUNES*/
				OR I.SMM_MED = '903'/*JOSÉ FERREIRA*/)
   			AND O.OSM_CNV = C.CNV_COD
			AND C.CNV_CAIXA_FATURA = 'C' 
			AND SMM_PAC_REG NOT IN (SELECT PAC_REG 
						FROM PAC 
						WHERE PAC_NOME LIKE '%TESTE %')

/*HONORÁRIOS CONSULTAS PARTICULAR MÉDICO EXTERNO*/
SELECT O.OSM_SERIE AS "SÉRIE", O.OSM_NUM AS "NÚMERO", convert(varchar(2),month(O.OSM_DTHR))+'/'+convert(varchar(4),year(O.OSM_DTHR)) as "MÊS/ANO", I.SMM_NUM AS "ITEM", I.SMM_COD AS "CÓDIGO", P.SMK_NOME AS "DESCRIÇÃO", I.SMM_MED AS "MÉDICO", C.CNV_NOME AS "CONVÊNIO", I.SMM_STR AS "SETOR", I.SMM_QT AS "QUANTIDADE", ISNULL(I.SMM_VLR,0) AS "VALOR", ((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL1,0))
		+(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL2,0))
		+(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL6,0)))*0.83
		FROM HOSSRVSMART.SMART.DBO.SMM I, 			
		HOSSRVSMART.SMART.DBO.SMK P,
		HOSSRVSMART.SMART.DBO.CNV C, 
		HOSSRVSMART.SMART.DBO.MTE M,						
		HOSSRVSMART.SMART.DBO.OSM O,
		HOSSRVSMART.SMART.DBO.HON H
		WHERE I.SMM_OSM = O.OSM_NUM
			AND I.SMM_OSM_SERIE = O.OSM_SERIE
			AND I.SMM_HON_SEQ = H.HON_SEQ
			AND MONTH(O.OSM_DTHR) = @MES_ATUAL
			AND YEAR(O.OSM_DTHR) = @ANO_ATUAL
			AND M.MTE_OSM_SERIE = O.OSM_SERIE
			AND M.MTE_OSM = O.OSM_NUM
			AND M.MTE_IND_REC_NF = 'F'
			AND M.MTE_STATUS = 'D'
			AND I.SMM_COD = P.SMK_COD 
			AND I.SMM_TPCOD  = P.SMK_TIPO
			AND (I.SMM_STR = 'JCO' OR I.SMM_STR = 'JCH' OR I.SMM_STR = 'JCM')
			AND I.SMM_COD <> 'CONSUCOH' 
			AND I.SMM_MED <> '2845'/*ALLAN LUZ*/
			and I.SMM_MED <> '3429'/*Ana Candida*/
			and I.SMM_MED <> '2081'/*CLÉCIA VILANOVA*/
			and I.SMM_MED <> '2044'/*DANILO AMARAL*/
			and I.SMM_MED <> '19150'/*EUDO MENDONÇA*/
			and I.SMM_MED <> '2518'/*FÁBIO MORAIS*/
			and I.SMM_MED <> '1707'/*FÁBIO RIBAS*/
			and I.SMM_MED <> '3519'/*GUSTAVO MELO*/
			and I.SMM_MED <> '2036'/*JOAQUIM FONTES*/

			and I.SMM_MED <> '4366'/*Lydianne Lumack do Monte Agra*/
			and I.SMM_MED <> '1885'/*MÁRCIO PIMENTA*/
			and I.SMM_MED <> '935'/*MÁRIO URSULINO*/
			and I.SMM_MED <> '2245'/*MÕNICA ANDRADE*/
			and I.SMM_MED <> '3579'/*NAYANA MAYNART*/
			and I.SMM_MED <> '3616'/*TANIA NUNES*/
			and I.SMM_MED <> '903'/*JOSÉ FERREIRA*/
   			AND O.OSM_CNV = C.CNV_COD
			AND C.CNV_CAIXA_FATURA = 'C' 
			AND SMM_PAC_REG NOT IN (SELECT PAC_REG 
						FROM PAC 
						WHERE PAC_NOME LIKE '%TESTE %')

/*HONORÁRIOS CONSULTAS PARTICULAR SEM NOTA*/
SELECT O.OSM_SERIE AS "SÉRIE", O.OSM_NUM AS "NÚMERO", convert(varchar(2),month(O.OSM_DTHR))+'/'+convert(varchar(4),year(O.OSM_DTHR)) as "MÊS/ANO", I.SMM_NUM AS "ITEM", I.SMM_COD AS "CÓDIGO", P.SMK_NOME AS "DESCRIÇÃO", I.SMM_MED AS "MÉDICO", C.CNV_NOME AS "CONVÊNIO", I.SMM_STR AS "SETOR", I.SMM_QT AS "QUANTIDADE", ISNULL(I.SMM_VLR,0) AS "VALOR", ((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL1,0))
		+(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL2,0))
		+(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - (ISNULL(H.HON_VL1,0) + ISNULL(H.HON_VL2,0) + ISNULL(H.HON_VL3,0) + ISNULL(H.HON_VL4,0) + ISNULL(H.HON_VL5,0) + ISNULL(H.HON_VL6,0)))/100)+(ISNULL(H.HON_VL6,0)))
		FROM HOSSRVSMART.SMART.DBO.SMM I, 			
		HOSSRVSMART.SMART.DBO.SMK P,
		HOSSRVSMART.SMART.DBO.CNV C, 
		HOSSRVSMART.SMART.DBO.MTE M,						
		HOSSRVSMART.SMART.DBO.OSM O,
		HOSSRVSMART.SMART.DBO.HON H
		WHERE I.SMM_OSM = O.OSM_NUM
			AND I.SMM_OSM_SERIE = O.OSM_SERIE
			AND I.SMM_HON_SEQ = H.HON_SEQ
			AND MONTH(O.OSM_DTHR) = @MES_ATUAL
			AND YEAR(O.OSM_DTHR) = @ANO_ATUAL
			AND M.MTE_OSM_SERIE = O.OSM_SERIE
			AND M.MTE_OSM = O.OSM_NUM
			AND M.MTE_IND_REC_NF = 'R'
			AND M.MTE_STATUS = 'D'
			AND I.SMM_COD = P.SMK_COD 
			AND I.SMM_TPCOD  = P.SMK_TIPO
   			AND O.OSM_CNV = C.CNV_COD
			AND C.CNV_CAIXA_FATURA = 'C' 
			AND (I.SMM_STR = 'JCO' OR I.SMM_STR = 'JCH' OR I.SMM_STR = 'JCM')
			AND I.SMM_COD <> 'CONSUCOH' 
			AND SMM_PAC_REG NOT IN (SELECT PAC_REG 
						FROM PAC 
						WHERE PAC_NOME LIKE '%TESTE %')


/*PEGA O CUSTO VARIAVEL DE CONSULTAS DO MES ATUAL(GERAL)----------------------
SET @HONORARIOS_CONSULTAS = ISNULL (@HONORARIOS_CONSULTAS_MEDINTERNO_CONVENIO,0)
+ ISNULL (@HONORARIOS_CONSULTAS_MEDEXTERNO_CONVENIO,0)
+ ISNULL (@HONORARIOS_CONSULTAS_MEDINTERNO_PARTICULAR,0)
+ ISNULL (@HONORARIOS_CONSULTAS_MEDEXTERNO_PARTICULAR,0)
+ ISNULL (@HONORARIOS_CONSULTAS_NC_PARTICULAR,0)

SElect @HONORARIOS_CONSULTAS*/