/*PEGA O CUSTO DE MATERIAIS DO SETOR DE LENTES DO MES ATUAL(GERAL)--------------------*/
SELECT ISNULL(SUM(MMA_VLR_PM * MMA_QTD),0)
			FROM MMA V, MAT M
			WHERE V.MMA_TIPO_ES = 'S'
			AND V.MMA_MAT_COD = M.MAT_COD
			AND MONTH(MMA_DATA_MOV) = 7
			AND YEAR(MMA_DATA_MOV) = 2014
			AND MMA_STR_COD = 'JLC'
			AND (MMA_TIPO_OPERACAO = 'S1'
			OR MMA_TIPO_OPERACAO = 'S2')				
			AND M.MAT_GMM_COD <> 1 
			AND M.MAT_GMM_COD <> 2
			AND M.MAT_GMM_COD <> 4
			AND M.MAT_GMM_COD <> 6
			AND M.MAT_GMM_COD <> 19
			AND M.MAT_GMM_COD <> 17
			AND M.MAT_GMM_COD <> 25
			AND M.MAT_GMM_COD <> 26
			AND M.MAT_GMM_COD <> 27
			AND M.MAT_GMM_COD <> 28
			AND M.MAT_GMM_COD <> 29
