select * from indicadores where nome = '32.01.07.02 - JARDINS Honorários Médicos (Exames)'
select * from indicadoressimples where idindicador = 154 order by data
uuuupdate indicadoressimples set valor = 1341.78 where idindicadoressimples = 12764 

/*HONORARIOS - EXAMES (CONVÊNIO MED. INTERNO)       */
SELECT I.SMM_MED AS "CÓDIGO", S.PSV_NOME AS "MÉDICO", SUM(ISNULL(I.SMM_VLR,0)) AS "VALOR", SUM(((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL1,0)*I.SMM_QT)) +(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL2,0)*I.SMM_QT)) +(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL6,0)*I.SMM_QT)))*0.88) AS "HONORARIOS" 
FROM HOSSRVSMART.SMART.DBO.SMM I, HOSSRVSMART.SMART.DBO.SMK P, HOSSRVSMART.SMART.DBO.PSV S, HOSSRVSMART.SMART.DBO.CNV C, HOSSRVSMART.SMART.DBO.OSM O, HOSSRVSMART.SMART.DBO.HON H 
WHERE I.SMM_OSM = O.OSM_NUM AND I.SMM_MED = S.PSV_COD AND I.SMM_OSM_SERIE = O.OSM_SERIE AND I.SMM_HON_SEQ = H.HON_SEQ AND 
O.OSM_DTHR >= '2015-01-01 00:00:00' AND O.OSM_DTHR <= '2015-02-01 00:00:00' 
AND I.SMM_SFAT <> 'C' AND I.SMM_TIPO_FATURA = 'E' AND I.SMM_COD = P.SMK_COD AND I.SMM_TPCOD = P.SMK_TIPO 
AND( I.SMM_STR = 'ARG' OR I.SMM_STR = 'ART' OR I.SMM_STR = 'AVL' OR I.SMM_STR = 'CV' OR I.SMM_STR = 'PAQ' OR I.SMM_STR = 'ECO' OR I.SMM_STR = 'ERG' OR I.SMM_STR = 'MIC' OR I.SMM_STR = 'OCT' OR I.SMM_STR = 'OCV' OR I.SMM_STR = 'OCZ' OR I.SMM_STR = 'OR' OR I.SMM_STR = 'RET' OR I.SMM_STR = 'REX' OR I.SMM_STR = 'TOP' OR I.SMM_STR = 'TPZ' OR I.SMM_STR = 'US' OR I.SMM_STR = 'YAG') 
AND (I.SMM_MED = '2845'/*ALLAN LUZ*/
				OR I.SMM_MED = '3429'/*Ana Candida*/
				OR I.SMM_MED = '2081'/*CLÉCIA VILANOVA*/
				OR I.SMM_MED = '2044'/*DANILO AMARAL*/
				OR I.SMM_MED = '19150'/*EUDO MENDONÇA*/
				OR I.SMM_MED = '2518'/*FÁBIO MORAIS*/
				OR I.SMM_MED = '1707'/*FÁBIO RIBAS*/
				OR I.SMM_MED = '3519'/*GUSTAVO MELO*/
				OR I.SMM_MED = '2036'/*JOAQUIM FONTES*/
		
				OR I.SMM_MED = '4366'/*Lydianne Lumack do Monte Agra*/
				OR I.SMM_MED = '1885'/*MÁRCIO PIMENTA*/
				OR I.SMM_MED = '935'/*MÁRIO URSULINO*/
				OR I.SMM_MED = '2245'/*MÕNICA ANDRADE*/
				OR I.SMM_MED = '3579'/*NAYANA MAYNART*/
				OR I.SMM_MED = '3616'/*TANIA NUNES*/
				OR I.SMM_MED = '903'/*JOSÉ FERREIRA*/) 
AND O.OSM_CNV = C.CNV_COD AND C.CNV_CAIXA_FATURA = 'F' AND SMM_PAC_REG NOT IN (SELECT PAC_REG FROM PAC WHERE PAC_NOME LIKE '%TESTE %') GROUP BY I.SMM_MED, S.PSV_NOME

/*HONORARIOS - EXAMES (CONVÊNIO MED. EXTERNO)       */
SELECT I.SMM_MED AS "CÓDIGO", S.PSV_NOME AS "MÉDICO", SUM(ISNULL(I.SMM_VLR,0)) AS "VALOR", SUM(((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL1,0)*I.SMM_QT)) +(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL2,0)*I.SMM_QT)) +(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL6,0)*I.SMM_QT)))*0.83) AS "HONORARIOS" 
FROM HOSSRVSMART.SMART.DBO.SMM I, HOSSRVSMART.SMART.DBO.SMK P, HOSSRVSMART.SMART.DBO.PSV S, HOSSRVSMART.SMART.DBO.CNV C, HOSSRVSMART.SMART.DBO.OSM O, HOSSRVSMART.SMART.DBO.HON H 
WHERE I.SMM_OSM = O.OSM_NUM AND I.SMM_MED = S.PSV_COD AND I.SMM_OSM_SERIE = O.OSM_SERIE AND I.SMM_HON_SEQ = H.HON_SEQ 
and O.OSM_DTHR >= '2015-01-01 00:00:00' AND O.OSM_DTHR <= '2015-02-01 00:00:00' 
AND I.SMM_SFAT <> 'C' AND I.SMM_TIPO_FATURA = 'E' AND I.SMM_COD = P.SMK_COD AND I.SMM_TPCOD = P.SMK_TIPO 
AND( I.SMM_STR = 'ARG' OR I.SMM_STR = 'ART' OR I.SMM_STR = 'AVL' OR I.SMM_STR = 'CV' OR I.SMM_STR = 'PAQ' OR I.SMM_STR = 'ECO' OR I.SMM_STR = 'ERG' OR I.SMM_STR = 'MIC' OR I.SMM_STR = 'OCT' OR I.SMM_STR = 'OCV' OR I.SMM_STR = 'OCZ' OR I.SMM_STR = 'OR' OR I.SMM_STR = 'RET' OR I.SMM_STR = 'REX' OR I.SMM_STR = 'TOP' OR I.SMM_STR = 'TPZ' OR I.SMM_STR = 'US' OR I.SMM_STR = 'YAG') 
AND I.SMM_MED <> '2845'/*ALLAN LUZ*/
			and I.SMM_MED <> '3429'/*Ana Candida*/
			and I.SMM_MED <> '2081'/*CLÉCIA VILANOVA*/
			and I.SMM_MED <> '2044'/*DANILO AMARAL*/
			and I.SMM_MED <> '19150'/*EUDO MENDONÇA*/
			and I.SMM_MED <> '2518'/*FÁBIO MORAIS*/
			and I.SMM_MED <> '1707'/*FÁBIO RIBAS*/
			and I.SMM_MED <> '3519'/*GUSTAVO MELO*/
			and I.SMM_MED <> '2036'/*JOAQUIM FONTES*/

			and I.SMM_MED <> '4366'/*Lydianne Lumack do Monte Agra*/
			and I.SMM_MED <> '1885'/*MÁRCIO PIMENTA*/
			and I.SMM_MED <> '935'/*MÁRIO URSULINO*/
			and I.SMM_MED <> '2245'/*MÕNICA ANDRADE*/
			and I.SMM_MED <> '3579'/*NAYANA MAYNART*/
			and I.SMM_MED <> '3616'/*TANIA NUNES*/
			and I.SMM_MED <> '903'/*JOSÉ FERREIRA*/  
AND O.OSM_CNV = C.CNV_COD AND C.CNV_CAIXA_FATURA = 'F' AND SMM_PAC_REG NOT IN (SELECT PAC_REG FROM PAC WHERE PAC_NOME LIKE '%TESTE %') GROUP BY I.SMM_MED, S.PSV_NOME

/*HONORARIOS - EXAMES (PARTICULAR MED. INTERNO)     */
SELECT I.SMM_MED AS "CÓDIGO", S.PSV_NOME AS "MÉDICO", SUM(ISNULL(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)),0)) AS "VALOR", SUM(((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL1,0)*I.SMM_QT)) +(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL2,0)*I.SMM_QT)) +(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL6,0)*I.SMM_QT)))*0.88) AS "HONORARIOS" 
FROM HOSSRVSMART.SMART.DBO.SMM I, HOSSRVSMART.SMART.DBO.PSV S, HOSSRVSMART.SMART.DBO.SMK P, HOSSRVSMART.SMART.DBO.MTE M, HOSSRVSMART.SMART.DBO.CNV C, HOSSRVSMART.SMART.DBO.OSM O, HOSSRVSMART.SMART.DBO.HON H 
WHERE I.SMM_OSM = O.OSM_NUM AND I.SMM_MED = S.PSV_COD AND I.SMM_OSM_SERIE = O.OSM_SERIE AND I.SMM_HON_SEQ = H.HON_SEQ 
and O.OSM_DTHR >= '2015-01-01 00:00:00' AND O.OSM_DTHR <= '2015-02-01 00:00:00' 
AND M.MTE_OSM_SERIE = O.OSM_SERIE AND M.MTE_OSM = O.OSM_NUM AND M.MTE_STATUS = 'D' AND M.MTE_IND_REC_NF = 'F' AND I.SMM_COD = P.SMK_COD AND I.SMM_TPCOD = P.SMK_TIPO 
AND( I.SMM_STR = 'ARG' OR I.SMM_STR = 'ART' OR I.SMM_STR = 'AVL' OR I.SMM_STR = 'CV' OR I.SMM_STR = 'PAQ' OR I.SMM_STR = 'ECO' OR I.SMM_STR = 'ERG' OR I.SMM_STR = 'MIC' OR I.SMM_STR = 'OCT' OR I.SMM_STR = 'OCV' OR I.SMM_STR = 'OCZ' OR I.SMM_STR = 'OR' OR I.SMM_STR = 'RET' OR I.SMM_STR = 'REX' OR I.SMM_STR = 'TOP' OR I.SMM_STR = 'TPZ' OR I.SMM_STR = 'US' OR I.SMM_STR = 'YAG') 
AND (I.SMM_MED = '2845'/*ALLAN LUZ*/
				OR I.SMM_MED = '3429'/*Ana Candida*/
				OR I.SMM_MED = '2081'/*CLÉCIA VILANOVA*/
				OR I.SMM_MED = '2044'/*DANILO AMARAL*/
				OR I.SMM_MED = '19150'/*EUDO MENDONÇA*/
				OR I.SMM_MED = '2518'/*FÁBIO MORAIS*/
				OR I.SMM_MED = '1707'/*FÁBIO RIBAS*/
				OR I.SMM_MED = '3519'/*GUSTAVO MELO*/
				OR I.SMM_MED = '2036'/*JOAQUIM FONTES*/
		
				OR I.SMM_MED = '4366'/*Lydianne Lumack do Monte Agra*/
				OR I.SMM_MED = '1885'/*MÁRCIO PIMENTA*/
				OR I.SMM_MED = '935'/*MÁRIO URSULINO*/
				OR I.SMM_MED = '2245'/*MÕNICA ANDRADE*/
				OR I.SMM_MED = '3579'/*NAYANA MAYNART*/
				OR I.SMM_MED = '3616'/*TANIA NUNES*/
				OR I.SMM_MED = '903'/*JOSÉ FERREIRA*/) 
AND O.OSM_CNV = C.CNV_COD AND C.CNV_CAIXA_FATURA = 'C' AND SMM_PAC_REG NOT IN (SELECT PAC_REG FROM PAC WHERE PAC_NOME LIKE '%TESTE %') GROUP BY I.SMM_MED, S.PSV_NOME 

/*HONORARIOS - EXAMES (PARTICULAR MED. EXTERNO)     */
SELECT I.SMM_MED AS "CÓDIGO", S.PSV_NOME AS "MÉDICO", SUM(ISNULL(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)),0)) AS "VALOR", SUM(((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL1,0)*I.SMM_QT)) +(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL2,0)*I.SMM_QT)) +(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL6,0)*I.SMM_QT)))*0.83) AS "HONORARIOS" 
FROM HOSSRVSMART.SMART.DBO.SMM I, HOSSRVSMART.SMART.DBO.PSV S, HOSSRVSMART.SMART.DBO.SMK P, HOSSRVSMART.SMART.DBO.CNV C, HOSSRVSMART.SMART.DBO.MTE M, HOSSRVSMART.SMART.DBO.OSM O, HOSSRVSMART.SMART.DBO.HON H 
WHERE I.SMM_OSM = O.OSM_NUM AND I.SMM_MED = S.PSV_COD AND I.SMM_OSM_SERIE = O.OSM_SERIE AND I.SMM_HON_SEQ = H.HON_SEQ 
and O.OSM_DTHR >= '2015-01-01 00:00:00' AND O.OSM_DTHR <= '2015-02-01 00:00:00' 
AND M.MTE_OSM_SERIE = O.OSM_SERIE AND M.MTE_OSM = O.OSM_NUM AND M.MTE_IND_REC_NF = 'F' AND M.MTE_STATUS = 'D' AND I.SMM_COD = P.SMK_COD AND I.SMM_TPCOD = P.SMK_TIPO 
AND( I.SMM_STR = 'ARG' OR I.SMM_STR = 'ART' OR I.SMM_STR = 'AVL' OR I.SMM_STR = 'CV' OR I.SMM_STR = 'PAQ' OR I.SMM_STR = 'ECO' OR I.SMM_STR = 'ERG' OR I.SMM_STR = 'MIC' OR I.SMM_STR = 'OCT' OR I.SMM_STR = 'OCV' OR I.SMM_STR = 'OCZ' OR I.SMM_STR = 'OR' OR I.SMM_STR = 'RET' OR I.SMM_STR = 'REX' OR I.SMM_STR = 'TOP' OR I.SMM_STR = 'TPZ' OR I.SMM_STR = 'US' OR I.SMM_STR = 'YAG') 
AND I.SMM_MED <> '2845'/*ALLAN LUZ*/
			and I.SMM_MED <> '3429'/*Ana Candida*/
			and I.SMM_MED <> '2081'/*CLÉCIA VILANOVA*/
			and I.SMM_MED <> '2044'/*DANILO AMARAL*/
			and I.SMM_MED <> '19150'/*EUDO MENDONÇA*/
			and I.SMM_MED <> '2518'/*FÁBIO MORAIS*/
			and I.SMM_MED <> '1707'/*FÁBIO RIBAS*/
			and I.SMM_MED <> '3519'/*GUSTAVO MELO*/
			and I.SMM_MED <> '2036'/*JOAQUIM FONTES*/

			and I.SMM_MED <> '4366'/*Lydianne Lumack do Monte Agra*/
			and I.SMM_MED <> '1885'/*MÁRCIO PIMENTA*/
			and I.SMM_MED <> '935'/*MÁRIO URSULINO*/
			and I.SMM_MED <> '2245'/*MÕNICA ANDRADE*/
			and I.SMM_MED <> '3579'/*NAYANA MAYNART*/
			and I.SMM_MED <> '3616'/*TANIA NUNES*/
			and I.SMM_MED <> '903'/*JOSÉ FERREIRA*/  
AND O.OSM_CNV = C.CNV_COD AND C.CNV_CAIXA_FATURA = 'C' AND SMM_PAC_REG NOT IN (SELECT PAC_REG FROM PAC WHERE PAC_NOME LIKE '%TESTE %') GROUP BY I.SMM_MED, S.PSV_NOME

/*HONORARIOS - EXAMES (PARTICULAR SN)               */
SELECT I.SMM_MED AS "CÓDIGO", S.PSV_NOME AS "MÉDICO", SUM(ISNULL(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)),0)) AS "VALOR", SUM(((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL1,0)*I.SMM_QT)) +(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL2,0)*I.SMM_QT)) +(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((ISNULL(H.HON_VL1,0)*I.SMM_QT) + (ISNULL(H.HON_VL2,0)*I.SMM_QT) + (ISNULL(H.HON_VL3,0)*I.SMM_QT) + (ISNULL(H.HON_VL4,0)*I.SMM_QT) + (ISNULL(H.HON_VL5,0)*I.SMM_QT) + (ISNULL(H.HON_VL6,0)*I.SMM_QT)))/100)+((ISNULL(H.HON_VL6,0)*I.SMM_QT)))) AS "HONORARIOS" 
FROM HOSSRVSMART.SMART.DBO.SMM I, HOSSRVSMART.SMART.DBO.SMK P, HOSSRVSMART.SMART.DBO.PSV S, HOSSRVSMART.SMART.DBO.CNV C, HOSSRVSMART.SMART.DBO.MTE M, HOSSRVSMART.SMART.DBO.OSM O, HOSSRVSMART.SMART.DBO.HON H 
WHERE I.SMM_OSM = O.OSM_NUM AND I.SMM_MED = S.PSV_COD AND I.SMM_OSM_SERIE = O.OSM_SERIE AND I.SMM_HON_SEQ = H.HON_SEQ 
and O.OSM_DTHR >= '2015-01-01 00:00:00' AND O.OSM_DTHR <= '2015-02-01 00:00:00' 
AND M.MTE_OSM_SERIE = O.OSM_SERIE AND M.MTE_OSM = O.OSM_NUM AND M.MTE_IND_REC_NF = 'R' AND M.MTE_STATUS = 'D' AND I.SMM_COD = P.SMK_COD AND I.SMM_TPCOD = P.SMK_TIPO AND O.OSM_CNV = C.CNV_COD AND C.CNV_CAIXA_FATURA = 'C' 
AND( I.SMM_STR = 'ARG' OR I.SMM_STR = 'ART' OR I.SMM_STR = 'AVL' OR I.SMM_STR = 'CV' OR I.SMM_STR = 'PAQ' OR I.SMM_STR = 'ECO' OR I.SMM_STR = 'ERG' OR I.SMM_STR = 'MIC' OR I.SMM_STR = 'OCT' OR I.SMM_STR = 'OCV' OR I.SMM_STR = 'OCZ' OR I.SMM_STR = 'OR' OR I.SMM_STR = 'RET' OR I.SMM_STR = 'REX' OR I.SMM_STR = 'TOP' OR I.SMM_STR = 'TPZ' OR I.SMM_STR = 'US' OR I.SMM_STR = 'YAG') 
AND SMM_PAC_REG NOT IN (SELECT PAC_REG FROM PAC WHERE PAC_NOME LIKE '%TESTE %') GROUP BY I.SMM_MED, S.PSV_NOME