DECLARE @DIA_ATUAL INT
DECLARE @MES_ATUAL INT
DECLARE @ANO_ATUAL INT

SET @DIA_ATUAL = 03--DAY(GETDATE())
SET @MES_ATUAL = 08--MONTH(GETDATE())
SET @ANO_ATUAL = 2015--YEAR(GETDATE())

SELECT PAC.PAC_PRONT, 
       PAC.PAC_NOME, 
       psv.psv_fila_nome, 
       FLE.FLE_DTHR_CHEGADA, 
       FLE.FLE_DTHR_REG, 
       FLE.FLE_DTHR_ATENDIMENTO, 
       FLE.FLE_DTHR_FINAL,
	fle.fle_usr_login,
Convert(varchar(10),(ISNULL(fle.FLE_DTHR_ATENDIMENTO,ISNULL(Fle.FLE_DTHR_FINAL,GETDATE())) - Fle.FLE_DTHR_CHEGADA),108) AS 'TP. DE ESPERA',
Convert(varchar(10),ISNULL(Fle.FLE_DTHR_FINAL,GETDATE()) - ISNULL(Fle.FLE_DTHR_ATENDIMENTO,ISNULL(Fle.FLE_DTHR_FINAL,GETDATE())),108) AS 'TP DE ATENDIMENTO'
 FROM PAC, FLE, PSV 
 WHERE (  FLE.FLE_PSV_COD = PSV.PSV_COD  ) AND 
       (  FLE.FLE_PAC_REG = PAC.PAC_REG  ) 
			AND DAY(FLE.FLE_DTHR_ATENDIMENTO) = @DIA_ATUAL
			AND MONTH(FLE.FLE_DTHR_ATENDIMENTO) = @MES_ATUAL
			AND YEAR(FLE.FLE_DTHR_ATENDIMENTO) = @ANO_ATUAL
		--and psv.psv_fila_nome = 'FOCUS - LENTES'
		--AND PSV.PSV_COD = 2
		and pac_reg = 2024228

 ORDER BY PAC.PAC_PRONT ASC, 
       FLE.FLE_DTHR_CHEGADA ASC,
		FLE.FLE_DTHR_REG ASC

--SELECT * FROM fle



--Carlos Lucio de Mello 9940-3867 / 9963-8480

