use smart
SELECT F.FLE_PAC_REG AS 'PACIENTE', C.PAC_NOME AS 'NOME', F.FLE_PSV_COD AS 'COD. FILA', f.fle_status,
P.PSV_FILA_NOME AS 'FILA',
str.str_nome as 'Setor',
f.fle_osm_num as 'OS',
F.FLE_DTHR_MARCADA AS 'AGENDAMENTO',
Convert(varchar(10),F.FLE_DTHR_CHEGADA,103) AS 'CHEGADA', 
F.FLE_DTHR_ATENDIMENTO AS 'ATENDIMENTO', 
Convert(varchar(10),(ISNULL(F.FLE_DTHR_ATENDIMENTO,ISNULL(F.FLE_DTHR_FINAL,GETDATE())) - F.FLE_DTHR_CHEGADA),108) AS 'TP. DE ESPERA',
F.FLE_DTHR_FINAL AS 'ENCERRAMENTO', 
Convert(varchar(10),ISNULL(F.FLE_DTHR_FINAL,GETDATE()) - ISNULL(F.FLE_DTHR_ATENDIMENTO,ISNULL(F.FLE_DTHR_FINAL,GETDATE())),108) AS 'TP DE ATENDIMENTO',
--F.FLE_DTHR_FINAL - F.FLE_DTHR_ATENDIMENTO,
F.FLE_USR_ATENDIMENTO AS 'USUÁRIO',
F.FLE_USR_FINAL AS 'US. FINAL'
FROM FLE F, PSV P, PAC C, str
WHERE F.FLE_PSV_COD = P.PSV_COD 
AND YEAR(F.FLE_DTHR_REG) = 2015
AND Month(F.FLE_DTHR_REG) = 7
--AND day(F.FLE_DTHR_REG) = 28
AND F.FLE_PSV_COD = 2 --in (/*2, 7,*/ 77)
AND C.PAC_REG = F.FLE_PAC_REG
and str.str_cod = f.fle_str_cod
/*and f.fle_pac_reg = 432565*/
and f.fle_status = 'X'
and Convert(varchar(10),ISNULL(F.FLE_DTHR_FINAL,GETDATE()) - ISNULL(F.FLE_DTHR_ATENDIMENTO,ISNULL(F.FLE_DTHR_FINAL,GETDATE())),108) < '00:01:00'
ORDER BY F.FLE_PAC_REG--F.FLE_DTHR_CHEGADA

select * from psv where psv_fila_nome like '%lente%'
select * from fle where /*fle_osm_num is not null and fle_dthr_atendimento > '2015-07-01'  and */ FLE_PSV_COD in (2, 7, 77)

SELECT
P.PSV_FILA_NOME AS 'FILA',
Convert(varchar(10),F.FLE_DTHR_CHEGADA,103) AS 'CHEGADA', 
Convert(varchar(10),(ISNULL(F.FLE_DTHR_ATENDIMENTO,ISNULL(F.FLE_DTHR_FINAL,GETDATE())) - F.FLE_DTHR_CHEGADA),108) AS 'TP. DE ESPERA',
Convert(varchar(10),ISNULL(F.FLE_DTHR_FINAL,GETDATE()) - ISNULL(F.FLE_DTHR_ATENDIMENTO,ISNULL(F.FLE_DTHR_FINAL,GETDATE())),108) AS 'TP DE ATENDIMENTO'
FROM FLE F, PSV P, PAC C
WHERE F.FLE_PSV_COD = P.PSV_COD
AND YEAR(F.FLE_DTHR_REG) = 2014
/*AND F.FLE_PSV_COD = 935*/
AND C.PAC_REG = F.FLE_PAC_REG
ORDER BY F.FLE_DTHR_CHEGADA