/*DECLARACAO DE VARIAVEIS*/

DECLARE @DATAATUAL DATETIME
DECLARE @MES_ATUAL INT
DECLARE @ANO_ATUAL INT
DECLARE @COD_IND INT
DECLARE @MATERIAL_LENTES DECIMAL(12,2)

/*PEGA O ANO E MES ATUAL*/
SET @MES_ATUAL = 9/*MONTH(GETDATE())*/
SET @ANO_ATUAL = 2014/*YEAR(GETDATE())*/
SET @DATAATUAL = GETDATE()

/*DECLARA O CODIGO DO INDICADOR A SER ALIMENTADO*/
SET @COD_IND = 417


/*PEGA O CUSTO DE MATERIAIS DO SETOR DE LENTES DO MES ATUAL(GERAL)--------------------
SET @MATERIAL_LENTES = (SELECT ISNULL(SUM(MMA_VLR_PM * MMA_QTD),0)*/

select V.MMA_MAT_COD AS "CÓDIGO", V.MMA_DATA_MOV AS "DATA", 
V.MMA_STR_COD AS "SETOR", M.MAT_DESC_COMPLETA AS "DESCRICAO", 
g.gmm_nome as "Grupo",
(isnull(V.MMA_VLR_PM,0)) AS "VALOR UNITÁRIO", 
(isnull(V.MMA_QTD,0)) AS "QUANTIDADE", 
(ISNULL(V.MMA_VLR_PM * V.MMA_QTD,0)) AS "VALOR"   

			FROM MMA V, MAT M, gmm g
			WHERE V.MMA_TIPO_ES = 'S'
			AND V.MMA_MAT_COD = M.MAT_COD
			and m.mat_gmm_cod = g.gmm_cod
			AND MONTH(MMA_DATA_MOV) = 9/*@MES_ATUAL*/
			AND YEAR(MMA_DATA_MOV) = 2014/*@ANO_ATUAL*/
			AND MMA_STR_COD = 'FLL'
			AND (MMA_TIPO_OPERACAO = 'S1'
			OR MMA_TIPO_OPERACAO = 'S2')				
			AND M.MAT_GMM_COD <> 1 
			AND M.MAT_GMM_COD <> 2
			AND M.MAT_GMM_COD <> 4
			AND M.MAT_GMM_COD <> 6
			AND M.MAT_GMM_COD <> 19
			AND M.MAT_GMM_COD <> 17
			AND M.MAT_GMM_COD <> 25
			AND M.MAT_GMM_COD <> 26
			AND M.MAT_GMM_COD <> 27
			AND M.MAT_GMM_COD <> 28
			AND M.MAT_GMM_COD <> 29/*)
group by V.MMA_MAT_COD, M.MAT_DESC_COMPLETA, g.gmm_nome*/

/*INSERCAO OU ATUALIZACAO DOS DADOS
IF NOT EXISTS (SELECT S.IDINDICADORESSIMPLES
		FROM 		[HOSSRVSMART].STRATWS.DBO.INDICADORESSIMPLES S
		WHERE S.IDINDICADOR = @COD_IND
		AND MONTH(S.DATA) = @MES_ATUAL
		AND YEAR(S.DATA) = @ANO_ATUAL)
BEGIN
	INSERT INTO [HOSSRVSMART].STRATWS.DBO.INDICADORESSIMPLES
			(DATA,
			IDINDICADOR,
			VALOR,
			DATEUPDATED)
			VALUES(@DATAATUAL,
				@COD_IND,
				@MATERIAL_LENTES,
				@DATAATUAL)
END
ELSE
BEGIN
	UPDATE [HOSSRVSMART].STRATWS.DBO.INDICADORESSIMPLES
	SET VALOR = @MATERIAL_LENTES, DATEUPDATED = @DATAATUAL  
	WHERE IDINDICADOR = @COD_IND
		AND MONTH(DATA) = @MES_ATUAL
		AND YEAR(DATA) = @ANO_ATUAL
END
ENCERRA INTEGRACAO*/

