

SELECT I.SMM_COD AS "CÓDIGO", P.SMK_NOME AS "DESCRIÇÃO", C.CNV_NOME AS "CONVÊNIO",  SUM (I.SMM_QT) AS "QUANTIDADE", o.osm_num as Num_OS, o.osm_dthr as Data_Hora
			FROM HOSSRVSMART.SMART.DBO.SMM I,  
				HOSSRVSMART.SMART.DBO.MTE M,
                                HOSSRVSMART.SMART.DBO.CNV C, 
				HOSSRVSMART.SMART.DBO.SMK P, 
				HOSSRVSMART.SMART.DBO.OSM O 
			WHERE I.SMM_OSM = O.OSM_NUM
			AND I.SMM_OSM_SERIE = O.OSM_SERIE
			AND M.MTE_OSM_SERIE = O.OSM_SERIE
			AND M.MTE_OSM = O.OSM_NUM
                        AND O.OSM_CNV = C.CNV_COD 
			AND M.MTE_STATUS = 'D'
			AND O.OSM_DTHR >= '2014-09-01'/*@PERINICIAL*/
			AND O.OSM_DTHR <= '2014-09-30'/*@PERFINAL*/
			AND I.SMM_SFAT <> 'C'
			AND I.SMM_COD = P.SMK_COD 
			AND I.SMM_TPCOD  = P.SMK_TIPO
			AND I.SMM_COD <> '261'
			AND I.SMM_COD <> 'COPER'
			AND I.SMM_STR = 'jlc'
			AND SMM_PAC_REG NOT IN (SELECT PAC_REG 
						FROM PAC 
						WHERE PAC_NOME LIKE '%TESTE %')
GROUP BY I.SMM_COD, P.SMK_NOME, C.CNV_NOME, o.osm_num, o.osm_dthr 
ORDER BY P.SMK_NOME