SELECT v.mma_sma_serie, v.mma_sma_num as "No.Solic", V.MMA_TIPO_OPERACAO, V.MMA_DATA_MOV AS "DATA",V.MMA_MAT_COD AS "CÓDIGO",  V.MMA_STR_COD AS "SETOR", M.MAT_DESC_COMPLETA AS "DESCRICAO", replace(cast(V.MMA_VLR_PM as numeric(10,2)),'.',',') AS "VALOR UNITÁRIO", V.MMA_QTD AS "QUANTIDADE", replace(cast(ISNULL(V.MMA_VLR_PM * V.MMA_QTD,0) as numeric(10,2)),'.',',') AS "VALOR", v.mma_serie, v.mma_num
FROM MMA V, MAT M 
WHERE V.MMA_TIPO_ES = 'S' 
AND V.MMA_MAT_COD = M.MAT_COD 
AND V.MMA_DATA_MOV >= '2015-03-01 00:00:000' 
AND V.MMA_DATA_MOV <= '2015-04-01 00:00:000'  
AND V.MMA_STR_COD = 'CC' 
AND (V.MMA_TIPO_OPERACAO = 'S1' OR V.MMA_TIPO_OPERACAO = 'S2') 
AND M.MAT_GMM_COD <> 1 
AND M.MAT_GMM_COD <> 2 
AND M.MAT_GMM_COD <> 4 
AND M.MAT_GMM_COD <> 6 
AND M.MAT_GMM_COD <> 19 
AND M.MAT_GMM_COD <> 17 
AND M.MAT_GMM_COD <> 25 
AND M.MAT_GMM_COD <> 26 
AND M.MAT_GMM_COD <> 27 
AND M.MAT_GMM_COD <> 28 
AND M.MAT_GMM_COD <> 29 
ORDER BY V.MMA_num