

SELECT SMM.SMM_OSM_SERIE, SMM.SMM_OSM, OSM.OSM_STR, SMM.SMM_STR FROM SMM 
INNER JOIN OSM ON OSM.OSM_SERIE = SMM.SMM_OSM_SERIE AND OSM.OSM_NUM = SMM.SMM_OSM
INNER JOIN STR AS STRS ON STRS.STR_COD = OSM.OSM_STR
INNER JOIN STR AS STRE ON STRE.STR_COD = SMM.SMM_STR
WHERE
SMM.SMM_DTHR_EXEC >= '2016-01-01 00:00' AND
SMM.SMM_SFAT = 'F' AND
STRS.STR_STR_COD <> STRE.STR_STR_COD


SELECT * FROM SMM