select i.smm_osm_serie "OS Serie", i.smm_osm "OS Num", i.smm_sfat "Status Fat"
			FROM HOSSRVSMART.SMART.DBO.SMM I, 
				HOSSRVSMART.SMART.DBO.CNV C,
				HOSSRVSMART.SMART.DBO.MTE M,   
				HOSSRVSMART.SMART.DBO.SMK P, 
				HOSSRVSMART.SMART.DBO.OSM O 
			WHERE I.SMM_OSM = O.OSM_NUM
			AND I.SMM_OSM_SERIE = O.OSM_SERIE
			AND M.MTE_OSM_SERIE = O.OSM_SERIE
			AND M.MTE_OSM = O.OSM_NUM
			AND M.MTE_STATUS = 'D'
			AND MONTH(O.OSM_DTHR) = 1
			AND YEAR(O.OSM_DTHR) = 2015
			AND I.SMM_SFAT <> 'C'
			AND I.SMM_COD = P.SMK_COD 
			AND I.SMM_TPCOD  = P.SMK_TIPO
   			AND O.OSM_CNV = C.CNV_COD 
			AND  O.OSM_CNV <> 'PFE' 
			AND  O.OSM_CNV <> 'PCN' 
			AND  O.OSM_CNV <> 'PTL'
			AND C.CNV_CAIXA_FATURA = 'C' 
			AND O.OSM_CNV <> '51' 
			AND I.SMM_TPCOD = 'S'
			AND I.SMM_COD <> 'COPER'
			AND I.SMM_STR = 'EXL' 
			AND P.SMK_CTF <> '5021'
			AND P.SMK_CTF <> '5037'
			AND P.SMK_CTF <> '5023'
			AND P.SMK_CTF <> '5022'
			AND P.SMK_CTF <> '5043'
			AND P.SMK_CTF <> '5038'
			AND P.SMK_CTF <> '1712'
 			AND I.SMM_COD <> 'HONOCIR'
			AND I.SMM_COD <> 'COPER'
			AND I.SMM_COD <> 'HON'
			AND I.SMM_COD NOT LIKE 'MM%'
			AND I.SMM_COD NOT LIKE 'MAT%'
			AND I.SMM_COD <> 'MEDSOL' 

			AND SMM_PAC_REG NOT IN (SELECT PAC_REG 
						FROM PAC 
						WHERE PAC_NOME LIKE '%TESTE %')

