/*SELECT ISNULL(SUM (I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR))),0)*/
SELECT ISNULL(SUM (I.SMM_QT),0)
			FROM HOSSRVSMART.SMART.DBO.SMM I, 
				HOSSRVSMART.SMART.DBO.CNV C,
				HOSSRVSMART.SMART.DBO.MTE M,   
				HOSSRVSMART.SMART.DBO.SMK P, 
				HOSSRVSMART.SMART.DBO.OSM O 
			WHERE I.SMM_OSM = O.OSM_NUM
			AND I.SMM_OSM_SERIE = O.OSM_SERIE
			AND M.MTE_OSM_SERIE = O.OSM_SERIE
			AND M.MTE_OSM = O.OSM_NUM
			AND M.MTE_STATUS = 'D'
			AND MONTH(O.OSM_DTHR) = 1
			AND YEAR(O.OSM_DTHR) = 2015
			AND I.SMM_SFAT <> 'C'
			AND I.SMM_COD = P.SMK_COD AND I.SMM_TPCOD  = P.SMK_TIPO
			AND I.SMM_STR = 'EXL'  
   			AND O.OSM_CNV = C.CNV_COD 
			AND  O.OSM_CNV <> 'PFE' 
			AND  O.OSM_CNV <> 'PCN' 
			AND  O.OSM_CNV <> 'PTL'
			AND C.CNV_CAIXA_FATURA = 'C' 
			AND O.OSM_CNV <> '51' 
			AND SMM_PAC_REG NOT IN (SELECT PAC_REG 
						FROM PAC 
						WHERE PAC_NOME LIKE '%TESTE %')

