/*DECLARACAO DE VARIAVEIS*/

DECLARE @DATAATUAL DATETIME
DECLARE @MES_ATUAL INT
DECLARE @ANO_ATUAL INT
DECLARE @COD_IND INT
DECLARE @HONORARIOS_CIRURGIAS_FATMEDICO_CONVENIO DECIMAL(12,2)

/*PEGA O ANO E MES ATUAL*/
SET @MES_ATUAL = MONTH(GETDATE())
SET @ANO_ATUAL = YEAR(GETDATE())
SET @DATAATUAL = GETDATE()
select @MES_ATUAL
select @ANO_ATUAL
select @DATAATUAL
/*DECLARA O CODIGO DO INDICADOR A SER ALIMENTADO*/
SET @COD_IND = 157


/*HONORÁRIOS CIRURGIAS CONVÊNIO FATURAMENTO DIRETO PARA MÉDICO 
SET @HONORARIOS_CIRURGIAS_FATMEDICO_CONVENIO = (*/

SELECT * /*H.HON_PC1, I.SMM_VLR , H.HON_VL1, I.SMM_QT, H.HON_VL2, I.SMM_QT, H.HON_VL3, I.SMM_QT, H.HON_VL4, I.SMM_QT, 
	H.HON_VL5, I.SMM_QT, H.HON_VL6, I.SMM_QT, H.HON_VL1, I.SMM_QT, H.HON_PC2, I.SMM_VLR, H.HON_VL1, I.SMM_QT, 
	H.HON_VL2, I.SMM_QT, H.HON_VL3, I.SMM_QT, H.HON_VL4, I.SMM_QT, H.HON_VL5, I.SMM_QT, H.HON_VL6, I.SMM_QT, 
	H.HON_VL2, I.SMM_QT, H.HON_PC6, I.SMM_VLR, H.HON_VL1, I.SMM_QT, H.HON_VL2, I.SMM_QT, H.HON_VL3, I.SMM_QT,
	H.HON_VL4, I.SMM_QT, H.HON_VL5, I.SMM_QT, H.HON_VL6, I.SMM_QT, H.HON_VL6, I.SMM_QT*/
		FROM HOSSRVSMART.SMART.DBO.SMM I, 			
		HOSSRVSMART.SMART.DBO.SMK P, 
		HOSSRVSMART.SMART.DBO.CNV C, 						
		HOSSRVSMART.SMART.DBO.OSM O,
		HOSSRVSMART.SMART.DBO.HON H
		WHERE I.SMM_OSM = O.OSM_NUM
			AND I.SMM_OSM_SERIE = O.OSM_SERIE
			AND I.SMM_HON_SEQ = H.HON_SEQ
			AND MONTH(O.OSM_DTHR) = @MES_ATUAL
			AND YEAR(O.OSM_DTHR) = @ANO_ATUAL
			AND I.SMM_SFAT <> 'C'
			AND I.SMM_TIPO_FATURA = 'M'
			AND I.SMM_COD = P.SMK_COD 
			AND I.SMM_TPCOD  = P.SMK_TIPO
			AND I.SMM_COD <> 'PCFACEC'
			AND I.SMM_COD <> 'VITRESUS'
			AND I.SMM_COD <> 'RETSUS'
			AND I.SMM_COD <> 'GLOUCOE'
			AND I.SMM_COD <> 'PC PTER'
			AND I.SMM_STR = 'CC'
			AND O.OSM_CNV = C.CNV_COD 
			AND  O.OSM_CNV <> 'PFE' 
			AND  O.OSM_CNV <> 'PCN' 
			AND  O.OSM_CNV <> 'PTL'
			AND C.CNV_CAIXA_FATURA = 'F' 
			AND SMM_PAC_REG NOT IN (SELECT PAC_REG 
						FROM PAC 
						WHERE PAC_NOME LIKE '%TESTE %')

/*INSERCAO OU ATUALIZACAO DOS DADOS
IF NOT EXISTS (SELECT S.IDINDICADORESSIMPLES
		FROM 		[HOSSRVSMART].STRATWS.DBO.INDICADORESSIMPLES S
		WHERE S.IDINDICADOR = @COD_IND
		AND MONTH(S.DATA) = @MES_ATUAL
		AND YEAR(S.DATA) = @ANO_ATUAL)
BEGIN
	INSERT INTO [HOSSRVSMART].STRATWS.DBO.INDICADORESSIMPLES
			(DATA,
			IDINDICADOR,
			VALOR,
			DATEUPDATED)
			VALUES(@DATAATUAL,
				@COD_IND,
				@HONORARIOS_CIRURGIAS_FATMEDICO_CONVENIO,
				@DATAATUAL)
END
ELSE
BEGIN
	UPDATE [HOSSRVSMART].STRATWS.DBO.INDICADORESSIMPLES
	SET VALOR = @HONORARIOS_CIRURGIAS_FATMEDICO_CONVENIO, DATEUPDATED = @DATAATUAL  
	WHERE IDINDICADOR = @COD_IND
		AND MONTH(DATA) = @MES_ATUAL
		AND YEAR(DATA) = @ANO_ATUAL
END
ENCERRA INTEGRACAO*/