use smart
SELECT F.FLE_PAC_REG AS 'PACIENTE', C.PAC_NOME AS 'NOME', F.FLE_PSV_COD AS 'COD. FILA',
P.PSV_FILA_NOME AS 'FILA',
str.str_nome as 'Setor',
f.fle_osm_num as 'OS',
F.FLE_DTHR_MARCADA AS 'AGENDAMENTO',
Convert(varchar(10),F.FLE_DTHR_CHEGADA,103) AS 'CHEGADA', 
F.FLE_DTHR_ATENDIMENTO AS 'ATENDIMENTO', 
Convert(varchar(10),(ISNULL(F.FLE_DTHR_ATENDIMENTO,ISNULL(F.FLE_DTHR_FINAL,GETDATE())) - F.FLE_DTHR_CHEGADA),108) AS 'TP. DE ESPERA',
F.FLE_DTHR_FINAL AS 'ENCERRAMENTO', 
Convert(varchar(10),ISNULL(F.FLE_DTHR_FINAL,GETDATE()) - ISNULL(F.FLE_DTHR_ATENDIMENTO,ISNULL(F.FLE_DTHR_FINAL,GETDATE())),108) AS 'TP DE ATENDIMENTO',
F.FLE_USR_ATENDIMENTO AS 'USUÁRIO',
F.FLE_USR_FINAL AS 'US. FINAL'
FROM FLE F, PSV P, PAC C, str
WHERE F.FLE_PSV_COD = P.PSV_COD 
AND YEAR(F.FLE_DTHR_REG) = 2014
AND F.FLE_PSV_COD = 935
AND C.PAC_REG = F.FLE_PAC_REG
and str.str_cod = f.fle_str_cod
/*and f.fle_pac_reg = 432565*/
ORDER BY F.FLE_DTHR_CHEGADA

SELECT
P.PSV_FILA_NOME AS 'FILA',
Convert(varchar(10),F.FLE_DTHR_CHEGADA,103) AS 'CHEGADA', 
Convert(varchar(10),(ISNULL(F.FLE_DTHR_ATENDIMENTO,ISNULL(F.FLE_DTHR_FINAL,GETDATE())) - F.FLE_DTHR_CHEGADA),108) AS 'TP. DE ESPERA',
Convert(varchar(10),ISNULL(F.FLE_DTHR_FINAL,GETDATE()) - ISNULL(F.FLE_DTHR_ATENDIMENTO,ISNULL(F.FLE_DTHR_FINAL,GETDATE())),108) AS 'TP DE ATENDIMENTO'
FROM FLE F, PSV P, PAC C
WHERE F.FLE_PSV_COD = P.PSV_COD
AND YEAR(F.FLE_DTHR_REG) = 2014
/*AND F.FLE_PSV_COD = 935*/
AND C.PAC_REG = F.FLE_PAC_REG
ORDER BY F.FLE_DTHR_CHEGADA