

update validasmart.dbo.item
set cmdsql_item =
'Select I.SMM_MED AS "CÓDIGO", S.PSV_NOME AS "MÉDICO", SUM(ISNULL(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)),0)) AS "VALOR", SUM(((ISNULL(H.HON_PC1,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((((ISNULL(H.HON_VL1,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL2,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL3,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL4,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL5,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL6,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT)))/100)+((((ISNULL(H.HON_VL1,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT)) +(ISNULL(H.HON_PC2,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((((ISNULL(H.HON_VL1,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL2,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL3,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL4,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL5,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL6,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT)))/100)+((((ISNULL(H.HON_VL2,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT)) +(ISNULL(H.HON_PC6,0)*(I.SMM_VLR - (I.SMM_VLR* (M.MTE_DESCONTO/M.MTE_VALOR)) - ((((ISNULL(H.HON_VL1,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL2,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL3,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL4,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL5,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT) + (((ISNULL(H.HON_VL6,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT)))/100)+((((ISNULL(H.HON_VL6,0)*I.SMM_QT)*I.SMM_QT)*I.SMM_QT)))*0.83) AS "HONORARIOS" 
FROM HOSSRVSMART.SMART.DBO.SMM I, HOSSRVSMART.SMART.DBO.SMK P, HOSSRVSMART.SMART.DBO.PSV S, HOSSRVSMART.SMART.DBO.CNV C, HOSSRVSMART.SMART.DBO.MTE M, HOSSRVSMART.SMART.DBO.OSM O, HOSSRVSMART.SMART.DBO.HON H 
WHERE 
I.SMM_OSM = O.OSM_NUM 
AND I.SMM_MED = S.PSV_COD 
AND I.SMM_OSM_SERIE = O.OSM_SERIE 
AND I.SMM_HON_SEQ = H.HON_SEQ 
AND O.OSM_DTHR >= @PERINICIAL 
AND O.OSM_DTHR <= @PERFINAL
AND M.MTE_OSM_SERIE = O.OSM_SERIE 
AND M.MTE_OSM = O.OSM_NUM 
AND M.MTE_IND_REC_NF = ''F'' 
AND M.MTE_STATUS = ''D'' 
AND I.SMM_COD = P.SMK_COD 
AND I.SMM_TPCOD = P.SMK_TIPO 
AND I.SMM_COD <> ''PCFACEC''
AND I.SMM_COD <> ''VITRESUS'' 
AND I.SMM_COD <> ''RETSUS'' 
AND I.SMM_COD <> ''GLOUCOE'' 
AND I.SMM_COD <> ''PC PTER'' 
AND I.SMM_STR = ''CC'' 
			AND I.SMM_MED <> ''2845''/*ALLAN LUZ*/
			and I.SMM_MED <> ''3429''/*Ana Candida*/
			and I.SMM_MED <> ''2081''/*CLÉCIA VILANOVA*/
			and I.SMM_MED <> ''2044''/*DANILO AMARAL*/
			and I.SMM_MED <> ''19150''/*EUDO MENDONÇA*/
			and I.SMM_MED <> ''2518''/*FÁBIO MORAIS*/
			and I.SMM_MED <> ''1707''/*FÁBIO RIBAS*/
			and I.SMM_MED <> ''3519''/*GUSTAVO MELO*/
			and I.SMM_MED <> ''2036''/*JOAQUIM FONTES*/
			and I.SMM_MED <> ''3159''/*Lusa Reis Silva*/
			and I.SMM_MED <> ''4366''/*Lydianne Lumack do Monte Agra*/
			and I.SMM_MED <> ''1885''/*MÁRCIO PIMENTA*/
			and I.SMM_MED <> ''935''/*MÁRIO URSULINO*/
			and I.SMM_MED <> ''2245''/*MÕNICA ANDRADE*/
			and I.SMM_MED <> ''3579''/*NAYANA MAYNART*/
			and I.SMM_MED <> ''3616''/*TANIA NUNES*/
			and I.SMM_MED <> ''903''/*JOSÉ FERREIRA*/
AND O.OSM_CNV = C.CNV_COD 
AND C.CNV_CAIXA_FATURA = ''C'' 
AND SMM_PAC_REG NOT IN (SELECT PAC_REG FROM PAC WHERE PAC_NOME LIKE ''%TESTE %'') 
GROUP BY I.SMM_MED, S.PSV_NOME'

where id_item = 68