use smart
SELECT V.MMA_MAT_COD AS "CÓDIGO", V.MMA_DATA_MOV AS "DATA", 
V.MMA_STR_COD AS "SETOR", M.MAT_DESC_COMPLETA AS "DESCRICAO", 
V.MMA_VLR_PM AS "VALOR UNITÁRIO", V.MMA_QTD AS "QUANTIDADE", 
ISNULL(V.MMA_VLR_PM * V.MMA_QTD,0) AS "VALOR"     FROM MMA V, MAT M     
WHERE V.MMA_TIPO_ES = 'S'     AND V.MMA_MAT_COD = M.MAT_COD     
AND MMA_DATA_MOV >= '2014/09/01'     
AND MMA_DATA_MOV <= '2014/09/30'     
AND MMA_STR_COD = 'FLL'    
AND (MMA_TIPO_OPERACAO = 'S1'     OR MMA_TIPO_OPERACAO = 'S2')        
AND M.MAT_GMM_COD <> 1      
AND M.MAT_GMM_COD <> 2     
AND M.MAT_GMM_COD <> 4     
AND M.MAT_GMM_COD <> 6     
AND M.MAT_GMM_COD <> 19     
AND M.MAT_GMM_COD <> 17  
AND M.MAT_GMM_COD <> 25 
AND M.MAT_GMM_COD <> 26 
AND M.MAT_GMM_COD <> 27 
AND M.MAT_GMM_COD <> 28 
AND M.MAT_GMM_COD <> 29 
ORDER BY V.MMA_DATA_MOV

select * from str